### ISSUE TITLE
eof error in run.sh

### ISSUE THREAD

**Issue by lbarnesdev** [impunitus/arkserver#1]
the eof error is caused by the if not being closed on line 38 of run.sh. I'm not that knowledgeable with bash scripting, but I added a fi after the cat and everything ran fine...really bad error description, but bash isn't known for being robust :D

**Comment by calebbutcher** [comment]
Been a little busy over the holidays, etc but I'll get this fixed over the next couple of days for you. Thanks for filing an issue 😃

**Comment by calebbutcher** [comment]
@lbarnesdev Pushed an update through, let me know if you are still running into any issues when/if you pull the update. Thanks!

**Comment by lbarnesdev** [comment]
everything is working, thanks.
